name: Playwright Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --project=chromium

      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Playwright Tests Passed
          to: rajesh@jupitermeta.io
          from: GitHub Actions
          body: |
            Playwright tests completed successfully.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
          secure: true.     